In [4]:
import pandas as pd
import numpy as np

rat_df = pd.read_csv('data/NYC_Rat_Sightings.csv')
RIR_df = pd.read_csv('data/NYC_Restaurant_Inspection_Results.csv')
print(rat_df.info())
print(RIR_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107049 entries, 0 to 107048
Data columns (total 52 columns):
Unique Key                        107049 non-null int64
Created Date                      107049 non-null object
Closed Date                       96129 non-null object
Agency                            107049 non-null object
Agency Name                       107049 non-null object
Complaint Type                    107049 non-null object
Descriptor                        107049 non-null object
Location Type                     107043 non-null object
Incident Zip                      106689 non-null float64
Incident Address                  97583 non-null object
Street Name                       97582 non-null object
Cross Street 1                    88705 non-null object
Cross Street 2                    88670 non-null object
Intersection Street 1             9296 non-null object
Intersection Street 2             9296 non-null object
Address Type                      106679 non-null object
City                              106683 non-null object
Landmark                          36 non-null object
Facility Type                     0 non-null float64
Status                            107049 non-null object
Due Date                          106931 non-null object
Resolution Action Updated Date    107046 non-null object
Community Board                   107049 non-null object
Borough                           107049 non-null object
X Coordinate (State Plane)        106300 non-null float64
Y Coordinate (State Plane)        106300 non-null float64
Park Facility Name                107049 non-null object
Park Borough                      107049 non-null object
School Name                       107049 non-null object
School Number                     107049 non-null object
School Region                     107049 non-null object
School Code                       107049 non-null object
School Phone Number               107049 non-null object
School Address                    107049 non-null object
School City                       107049 non-null object
School State                      107049 non-null object
School Zip                        107049 non-null object
School Not Found                  106130 non-null object
School or Citywide Complaint      0 non-null float64
Vehicle Type                      0 non-null float64
Taxi Company Borough              0 non-null float64
Taxi Pick Up Location             0 non-null float64
Bridge Highway Name               0 non-null float64
Bridge Highway Direction          0 non-null float64
Road Ramp                         0 non-null float64
Bridge Highway Segment            0 non-null float64
Garage Lot Name                   0 non-null float64
Ferry Direction                   0 non-null float64
Ferry Terminal Name               0 non-null float64
Latitude                          106300 non-null float64
Longitude                         106300 non-null float64
Location                          106300 non-null object
dtypes: float64(17), int64(1), object(34)
memory usage: 42.5+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387868 entries, 0 to 387867
Data columns (total 18 columns):
CAMIS                    387868 non-null int64
DBA                      387476 non-null object
BORO                     387868 non-null object
BUILDING                 387735 non-null object
STREET                   387864 non-null object
ZIPCODE                  387864 non-null float64
PHONE                    387851 non-null object
CUISINE DESCRIPTION      387868 non-null object
INSPECTION DATE          387868 non-null object
ACTION                   386697 non-null object
VIOLATION CODE           381747 non-null object
VIOLATION DESCRIPTION    381021 non-null object
CRITICAL FLAG            387868 non-null object
SCORE                    366119 non-null float64
GRADE                    191553 non-null object
GRADE DATE               189457 non-null object
RECORD DATE              387868 non-null object
INSPECTION TYPE          386697 non-null object
dtypes: float64(2), int64(1), object(15)
memory usage: 53.3+ MB
None

In [5]:
rat_df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
0,31464015,09/04/2015 12:00:00 AM,09/18/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Mixed Use Building,10006.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.707772,-74.012963,"(40.70777155363643, -74.01296309970473)"
1,31464024,09/04/2015 12:00:00 AM,10/28/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,Commercial Building,10306.0,2270 HYLAN BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.575209,-74.104547,"(40.575209242947444, -74.1045465185469)"
2,31464025,09/04/2015 12:00:00 AM,NaN,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,1-2 Family Dwelling,10310.0,758 POST AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.631236,-74.126878,"(40.63123555151668, -74.12687759748677)"
3,31464026,09/04/2015 12:00:00 AM,09/14/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Apt. Building,11206.0,198 SCHOLES STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.708987,-73.941207,"(40.70898692345805, -73.94120690238431)"
4,31464027,09/04/2015 12:00:00 AM,09/22/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Mixed Use Building,10462.0,2138 WALLACE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.854130,-73.864813,"(40.85413014360452, -73.86481331044513)"

In [6]:
RIR_df.head()

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,RECORD DATE,INSPECTION TYPE
0,41658103,CHOP SHOP,MANHATTAN,254,10 AVENUE,10001.0,2128200333,Asian,03/24/2015,Violations were cited in the following area(s).,08A,Facility not vermin proof. Harborage or condit...,Not Critical,34.0,NaN,NaN,01/17/2018,Cycle Inspection / Initial Inspection
1,41261148,EL VALLE RESTAURANT,BRONX,640,MELROSE AVENUE,10455.0,7185855858,"Latin (Cuban, Dominican, Puerto Rican, South &...",02/02/2015,Violations were cited in the following area(s).,10F,Non-food contact surface improperly constructe...,Not Critical,11.0,A,02/02/2015,01/17/2018,Cycle Inspection / Re-inspection
2,40389807,CHAMP GOURMET,MANHATTAN,30,BROAD STREET,10004.0,2123634000,American,06/24/2016,Violations were cited in the following area(s).,06C,Food not protected from potential source of co...,Critical,17.0,B,06/24/2016,01/17/2018,Cycle Inspection / Re-inspection
3,41574708,PRONTO RESTAURANT,STATEN ISLAND,3297,RICHMOND AVENUE,10312.0,7183562442,Pizza/Italian,01/13/2015,Violations were cited in the following area(s).,06C,Food not protected from potential source of co...,Critical,12.0,A,01/13/2015,01/17/2018,Cycle Inspection / Re-inspection
4,50064814,PURE GREEN,MANHATTAN,60,E 8TH ST,10003.0,2125290081,"Juice, Smoothies, Fruit Salads",08/31/2017,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,Not Critical,8.0,A,08/31/2017,01/17/2018,Pre-permit (Operational) / Re-inspection